enum:
- collection: timeseriesType
  description: Time series with double floating point data points.
  name: numeric
  neatId: http://purl.org/cognite/neat/neatId_12e55cfb_60be_482c_99b3_02c0edf950d1
  value: numeric
- collection: timeseriesType
  description: Time series with string data points.
  name: string
  neatId: http://purl.org/cognite/neat/neatId_5f9adb90_fad6_4d4e_ba7b_5a7e28fcc04c
  value: string
metadata:
  created: '2024-08-29T13:49:56.696000'
  creator: Anders Albert,Nikola Vasiljevic,Thorkild Stray
  description: Mapping from Classic to Core
  external_id: ClassicCoreMapping
  name: data_product data model
  role: DMS Architect
  space: mapping
  updated: '2024-08-29T13:49:56.696000'
  version: v1.0
properties:
- connection: reverse(property=assets)
  description: An automatically updated list of activities related to the asset.
  is_list: true
  name: Activities
  neatId: http://purl.org/cognite/neat/neatId_1fe7871c_f6e0_40ad_bc3b_d2ff70986d9b
  value_type: ClassicEvent
  view: ClassicAsset
  view_property: activities
- connection: reverse(property=parent)
  description: An automatically updated list of assets with this asset as their parent.
  is_list: true
  name: Children
  neatId: http://purl.org/cognite/neat/neatId_76c4ffb3_409a_41af_8431_ee6212825fce
  value_type: ClassicAsset
  view: ClassicAsset
  view_property: children
- container: cdf_cdm:CogniteDescribable
  container_property: description
  description: Description of the instance
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_fadae7fd_ac77_4c26_bfe8_d78ed13f91f9
  nullable: true
  value_type: text
  view: ClassicAsset
  view_property: description
- connection: reverse(property=asset)
  description: An automatically updated list of equipment related to the asset.
  is_list: true
  name: Equipment
  neatId: http://purl.org/cognite/neat/neatId_ce6851fe_6292_455e_b2f4_fc2fa1eac1fe
  value_type: ClassicEquipment
  view: ClassicAsset
  view_property: equipment
- connection: reverse(property=assets)
  description: An automatically updated list of files related to the asset.
  is_list: true
  name: Files
  neatId: http://purl.org/cognite/neat/neatId_906d7886_b9dd_4b30_850e_fdf9e20f7d4c
  value_type: ClassicFile
  view: ClassicAsset
  view_property: files
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_eb983130_95f3_4ff3_9ff9_0cdbee80fa55
  nullable: true
  value_type: text
  view: ClassicAsset
  view_property: labels
- container: cdf_cdm:CogniteDescribable
  container_property: name
  description: Name of the instance
  immutable: false
  index: name
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_b76eb741_cd49_4cee_9dd6_6eed480a2d3c
  nullable: true
  value_type: text
  view: ClassicAsset
  view_property: name
- connection: direct
  container: cdf_cdm:CogniteAsset
  container_property: assetHierarchy_parent
  description: The parent of the asset.
  immutable: false
  is_list: false
  name: Parent
  neatId: http://purl.org/cognite/neat/neatId_f9455ec3_3ab1_4e43_95a5_4324d2f0f87a
  nullable: true
  value_type: ClassicAsset
  view: ClassicAsset
  view_property: parentId
- connection: direct
  container: cdf_cdm:CogniteAsset
  container_property: assetHierarchy_path
  description: An automatically updated ordered list of this asset's ancestors, starting
    with the root asset. Enables subtree filtering to find all assets under a parent.
  immutable: false
  is_list: true
  name: Path
  neatId: http://purl.org/cognite/neat/neatId_493effe7_8181_49c1_a60e_ae5634058270
  nullable: true
  value_type: ClassicAsset
  view: ClassicAsset
  view_property: path
- connection: direct
  container: cdf_cdm:CogniteAsset
  container_property: assetHierarchy_root
  description: An automatically updated reference to the top-level asset of the hierarchy.
  immutable: false
  is_list: false
  name: Root
  neatId: http://purl.org/cognite/neat/neatId_24af56f2_a871_4908_88ec_6cd5d0ac458d
  nullable: true
  value_type: ClassicAsset
  view: ClassicAsset
  view_property: root
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_a5343965_96fe_4f6a_aedf_1c31bba6f54d
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicAsset
  view_property: source
- connection: reverse(property=assets)
  description: An automatically updated list of time series related to the asset.
  is_list: true
  name: Time series
  neatId: http://purl.org/cognite/neat/neatId_dc652eca_a470_42bd_be27_39a996021deb
  value_type: ClassicTimeSeries
  view: ClassicAsset
  view_property: timeSeries
- connection: reverse(property=equipment)
  description: An automatically updated list of activities related to the equipment.
  is_list: true
  name: Activities
  neatId: http://purl.org/cognite/neat/neatId_d64c0f48_71d6_4e87_99ec_f8b1ae58c28b
  value_type: ClassicEvent
  view: ClassicEquipment
  view_property: activities
- connection: direct
  container: cdf_cdm:CogniteEquipment
  container_property: asset
  description: The asset the equipment is related to.
  immutable: false
  is_list: false
  name: Asset
  neatId: http://purl.org/cognite/neat/neatId_c40e111e_19dd_44a2_9814_118a9cd3b80a
  nullable: true
  value_type: ClassicAsset
  view: ClassicEquipment
  view_property: asset
- connection: direct
  container: cdf_cdm:CogniteEquipment
  container_property: files
  description: A list of files the equipment relates to.
  immutable: false
  is_list: true
  name: Files
  neatId: http://purl.org/cognite/neat/neatId_ebd5b40e_895e_45d7_b0d2_20669c1de5bd
  nullable: true
  value_type: ClassicFile
  view: ClassicEquipment
  view_property: files
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_76263d79_f08a_427c_b83e_4fa55c40426d
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicEquipment
  view_property: source
- connection: reverse(property=equipment)
  description: An automatically updated list of time series related to the equipment.
  is_list: true
  name: Time series
  neatId: http://purl.org/cognite/neat/neatId_c56875ff_f32e_4e99_9897_449baa5ae01b
  value_type: ClassicTimeSeries
  view: ClassicEquipment
  view_property: timeSeries
- container: cdf_cdm:CogniteDescribable
  container_property: aliases
  description: Alternative names for the node
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_ef151265_c942_4246_b54f_737a13c8506b
  nullable: true
  value_type: text
  view: ClassicEvent
  view_property: aliases
- connection: direct
  container: cdf_cdm:CogniteActivity
  container_property: assets
  description: A list of assets the activity is related to.
  immutable: false
  is_list: true
  name: Assets
  neatId: http://purl.org/cognite/neat/neatId_7b47cf3c_0a54_4f45_a68d_c0e9fa556198
  nullable: true
  value_type: ClassicAsset
  view: ClassicEvent
  view_property: assetIds
- container: cdf_cdm:CogniteDescribable
  container_property: description
  description: Description of the instance
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_90a8df89_4f31_469f_8940_1ff7ac74ef58
  nullable: true
  value_type: text
  view: ClassicEvent
  view_property: description
- container: cdf_cdm:CogniteSchedulable
  container_property: endTime
  description: The actual end time of an activity (or similar that extends this)
  immutable: false
  index: endTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_5581c388_1913_46b3_a573_9592a077310f
  nullable: true
  value_type: timestamp
  view: ClassicEvent
  view_property: endTime
- connection: direct
  container: cdf_cdm:CogniteActivity
  container_property: equipment
  description: A list of equipment the activity is related to.
  immutable: false
  is_list: true
  name: Equipment
  neatId: http://purl.org/cognite/neat/neatId_38a3f4dd_a63e_441e_b47f_469fcb073d43
  nullable: true
  value_type: ClassicEquipment
  view: ClassicEvent
  view_property: equipment
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_9418db99_c4bb_41e2_8992_7b58f380265d
  nullable: true
  value_type: text
  view: ClassicEvent
  view_property: labels
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_eaf1cd71_2e00_45ee_a122_5fe7e3c3cb2d
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicEvent
  view_property: source
- container: cdf_cdm:CogniteSchedulable
  container_property: startTime
  description: The actual start time of an activity (or similar that extends this)
  immutable: false
  index: startTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_79d42175_40b7_46de_a1a9_ac2f75e4d86a
  nullable: true
  value_type: timestamp
  view: ClassicEvent
  view_property: startTime
- connection: direct
  container: cdf_cdm:CogniteActivity
  container_property: timeSeries
  description: A list of time series the activity is related to.
  immutable: false
  is_list: true
  name: Time series
  neatId: http://purl.org/cognite/neat/neatId_ab14ad7e_b50a_411b_82d8_f4b1dd32668a
  nullable: true
  value_type: ClassicTimeSeries
  view: ClassicEvent
  view_property: timeSeries
- connection: direct
  container: cdf_cdm:CogniteFile
  container_property: assets
  description: A list of assets this file is related to.
  immutable: false
  is_list: true
  name: Assets
  neatId: http://purl.org/cognite/neat/neatId_ddbf417a_20d8_49ba_bb68_f697b73f8430
  nullable: true
  value_type: ClassicAsset
  view: ClassicFile
  view_property: assetIds
- container: cdf_cdm:CogniteFile
  container_property: directory
  description: Contains the path elements from the source (if the source system has
    a file system hierarchy or similar.)
  immutable: false
  is_list: false
  name: Directory
  neatId: http://purl.org/cognite/neat/neatId_34927e5d_2ee8_4dbe_ae17_385845980975
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: directory
- connection: reverse(property=files)
  description: An automatically updated list of equipment this file is related to.
  is_list: true
  name: Equipment
  neatId: http://purl.org/cognite/neat/neatId_44f0cf23_e566_491e_9e59_626153049388
  value_type: ClassicEquipment
  view: ClassicFile
  view_property: equipment
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_9701f440_976e_4b76_a6ab_f42943fe5e99
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: labels
- container: cdf_cdm:CogniteFile
  container_property: mimeType
  description: The MIME type of the file.
  immutable: false
  is_list: false
  name: MIME type
  neatId: http://purl.org/cognite/neat/neatId_729466bb_25e2_42dc_a120_da7f0598e934
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: mimeType
- container: cdf_cdm:CogniteDescribable
  container_property: name
  description: Name of the instance
  immutable: false
  index: name
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_6faf4ff6_9690_4cf4_a846_e82258a74823
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: name
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_9e6dc9a6_7770_451b_aee8_d275255eebe7
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicFile
  view_property: source
- container: cdf_cdm:CogniteSourceable
  container_property: sourceCreatedTime
  description: When the instance was created in source system (if available)
  immutable: false
  index: sourceCreatedTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_0dba587e_c182_4d6d_a9e5_2dedb6d2f75f
  nullable: true
  value_type: timestamp
  view: ClassicFile
  view_property: sourceCreatedTime
- container: cdf_cdm:CogniteSourceable
  container_property: sourceUpdatedTime
  description: When the instance was last updated in the source system (if available)
  immutable: false
  index: sourceUpdatedTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_abb2c94f_3622_4d6a_8643_99aebc308448
  nullable: true
  value_type: timestamp
  view: ClassicFile
  view_property: sourceModifiedTime
- container: cdf_cdm:CogniteDescribable
  container_property: name
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_7ff8a8c8_1ce7_4f16_af52_63308b049586
  nullable: true
  value_type: text
  view: ClassicSourceSystem
  view_property: name
- connection: reverse(property=timeSeries)
  description: An automatically updated list of activities the time series is related
    to.
  is_list: true
  name: Activities
  neatId: http://purl.org/cognite/neat/neatId_9f48d2ae_46bc_44fc_83d6_e65ff3048b10
  value_type: ClassicEvent
  view: ClassicTimeSeries
  view_property: activities
- connection: direct
  container: cdf_cdm:CogniteTimeSeries
  container_property: assets
  description: A list of assets the time series is related to.
  immutable: false
  is_list: true
  name: Assets
  neatId: http://purl.org/cognite/neat/neatId_d0ca2734_86e2_4dfe_8b80_8fa19d32a7e7
  nullable: true
  value_type: ClassicAsset
  view: ClassicTimeSeries
  view_property: assetId
- container: cdf_cdm:CogniteDescribable
  container_property: description
  description: Description of the instance
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_7789be71_2900_4a41_9d5c_800784b78a3b
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: description
- connection: direct
  container: cdf_cdm:CogniteTimeSeries
  container_property: equipment
  description: A list of equipment the time series is related to.
  immutable: false
  is_list: true
  name: Equipment
  neatId: http://purl.org/cognite/neat/neatId_641ade9e_f5f2_4acc_beec_f23bce104997
  nullable: true
  value_type: ClassicEquipment
  view: ClassicTimeSeries
  view_property: equipment
- container: cdf_cdm:CogniteTimeSeries
  container_property: isStep
  default: 0
  description: Specifies whether the time series is a step time series or not.
  immutable: false
  is_list: false
  name: Is step
  neatId: http://purl.org/cognite/neat/neatId_7cc34589_3792_434b_ac7d_87b4cbf40687
  nullable: false
  value_type: boolean
  view: ClassicTimeSeries
  view_property: isStep
- container: cdf_cdm:CogniteTimeSeries
  container_property: type
  description: Specifies the data type of the data points.
  immutable: true
  is_list: false
  name: Type
  neatId: http://purl.org/cognite/neat/neatId_6d8b8de3_22bc_46eb_9643_cc9d2d85745b
  nullable: false
  value_type: enum(collection=timeseriesType)
  view: ClassicTimeSeries
  view_property: isString
- container: cdf_cdm:CogniteDescribable
  container_property: aliases
  description: Alternative names for the node
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_aaca9ee2_7ca6_4c0f_8422_6703c98d3ee3
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: legacyName
- container: cdf_cdm:CogniteDescribable
  container_property: name
  description: Name of the instance
  immutable: false
  index: name
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_a031170a_daf7_4e14_b664_ee1eda4f98c9
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: name
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_b2d71ecb_c9e2_4e35_b04c_4a8f59645622
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: securityCategories
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_2c65ca17_9eb3_4b18_a11e_fa46c6cec923
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicTimeSeries
  view_property: source
- container: cdf_cdm:CogniteTimeSeries
  container_property: sourceUnit
  description: The unit specified in the source system.
  immutable: false
  is_list: false
  name: Source unit
  neatId: http://purl.org/cognite/neat/neatId_00456ce8_8572_4500_8258_bbe07d5dfb27
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: unit
- connection: direct
  container: cdf_cdm:CogniteTimeSeries
  container_property: unit
  description: The unit of the time series.
  immutable: false
  is_list: false
  name: Unit
  neatId: http://purl.org/cognite/neat/neatId_2bc4cb17_d8ac_40b9_a410_f36e5bbd57dc
  nullable: true
  value_type: cdf_cdm:CogniteUnit(version=v1)
  view: ClassicTimeSeries
  view_property: unitExternalId
views:
- description: Represents a single unit of measurement
  implements: cdf_cdm:CogniteDescribable(version=v1)
  in_model: true
  neatId: http://purl.org/cognite/neat/neatId_8a663a54_b4bf_4746_972f_c665e72470df
  view: cdf_cdm:CogniteUnit(version=v1)
- description: Assets represent systems that support industrial functions or processes.
    Assets are often called 'functional location'.
  implements: cdf_cdm:CogniteAsset(version=v1)
  in_model: true
  name: Asset
  neatId: http://purl.org/cognite/neat/neatId_af3855ac_72c3_494a_b925_e99527020031
  view: ClassicAsset
- description: Equipment represents physical supplies or devices.
  implements: cdf_cdm:CogniteEquipment(version=v1)
  in_model: true
  name: Equipment
  neatId: http://purl.org/cognite/neat/neatId_1894d6d9_88d3_4a0e_8888_d7d9fdf9a4d1
  view: ClassicEquipment
- description: Represents activities. Activities typically happen over a period and
    have a start and end time.
  implements: cdf_cdm:CogniteActivity(version=v1)
  in_model: true
  name: Activity
  neatId: http://purl.org/cognite/neat/neatId_4b071ae8_956d_4b0f_aff8_9651f1942c68
  view: ClassicEvent
- description: Represents files.
  implements: cdf_cdm:CogniteFile(version=v1)
  in_model: true
  name: File
  neatId: http://purl.org/cognite/neat/neatId_48e36681_a7b2_4a87_b475_92168f5a42e3
  view: ClassicFile
- description: The CogniteSourceSystem core concept is used to standardize the way
    source system is stored.
  implements: cdf_cdm:CogniteSourceSystem(version=v1)
  in_model: true
  neatId: http://purl.org/cognite/neat/neatId_c7a65b9c_35de_49cd_a361_98b92a241334
  view: ClassicSourceSystem
- description: Represents a series of data points in time order.
  implements: cdf_cdm:CogniteTimeSeries(version=v1)
  in_model: true
  name: Time series
  neatId: http://purl.org/cognite/neat/neatId_4d198457_0f47_467d_ba61_193f59259e41
  view: ClassicTimeSeries
