enum:
- collection: timeseriesType
  description: Time series with double floating point data points.
  name: numeric
  neatId: http://purl.org/cognite/neat/neatId_d4e42064_7c60_4bfc_b629_a873345f0ee2
  value: numeric
- collection: timeseriesType
  description: Time series with string data points.
  name: string
  neatId: http://purl.org/cognite/neat/neatId_8bb46fae_572d_464a_bc61_1055b0aa6c5d
  value: string
metadata:
  created: '2024-08-29T13:49:56.696000'
  creator: Anders Albert,Nikola Vasiljevic,Thorkild Stray
  description: Mapping from Classic to Core
  external_id: ClassicCoreMapping
  name: data_product data model
  role: DMS Architect
  space: mapping
  updated: '2024-08-29T13:49:56.696000'
  version: v1.0
properties:
- container: cdf_cdm:CogniteDescribable
  container_property: description
  description: Description of the instance
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_d887305d_af9d_4843_af6e_4115a7217d90
  nullable: true
  value_type: text
  view: ClassicAsset
  view_property: description
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_105a0fee_3942_4a6b_9d25_74d46d09c209
  nullable: true
  value_type: text
  view: ClassicAsset
  view_property: labels
- container: cdf_cdm:CogniteDescribable
  container_property: name
  description: Name of the instance
  immutable: false
  index: name
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_9559ecd6_a585_4fb9_90b7_7301da5f2170
  nullable: true
  value_type: text
  view: ClassicAsset
  view_property: name
- connection: direct
  container: cdf_cdm:CogniteAsset
  container_property: assetHierarchy_parent
  description: The parent of the asset.
  immutable: false
  is_list: false
  name: Parent
  neatId: http://purl.org/cognite/neat/neatId_fdc3280b_0d11_4e66_b2b5_8f37a398bed9
  nullable: true
  value_type: ClassicAsset
  view: ClassicAsset
  view_property: parentId
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_247e5b5d_4caf_4312_bd5b_341ed3fc3a03
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicAsset
  view_property: source
- container: cdf_cdm:CogniteDescribable
  container_property: aliases
  description: Alternative names for the node
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_7412eae6_e77c_41b7_92ca_737798f5844a
  nullable: true
  value_type: text
  view: ClassicEvent
  view_property: aliases
- connection: direct
  container: cdf_cdm:CogniteActivity
  container_property: assets
  description: A list of assets the activity is related to.
  immutable: false
  is_list: true
  name: Assets
  neatId: http://purl.org/cognite/neat/neatId_439538ba_610d_4300_a8cd_aa51dbbf5c1a
  nullable: true
  value_type: ClassicAsset
  view: ClassicEvent
  view_property: assetIds
- container: cdf_cdm:CogniteDescribable
  container_property: description
  description: Description of the instance
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_8ab69b21_b84e_4374_a2bd_6b7e6321f22d
  nullable: true
  value_type: text
  view: ClassicEvent
  view_property: description
- container: cdf_cdm:CogniteSchedulable
  container_property: endTime
  description: The actual end time of an activity (or similar that extends this)
  immutable: false
  index: endTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_fce69deb_af37_4c49_b1cf_caf569563ba7
  nullable: true
  value_type: timestamp
  view: ClassicEvent
  view_property: endTime
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_0ed58b00_11ab_4774_9c66_d2eabc5f8f42
  nullable: true
  value_type: text
  view: ClassicEvent
  view_property: labels
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_b0c7d726_6504_4189_896d_1b978d9ef5b2
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicEvent
  view_property: source
- container: cdf_cdm:CogniteSchedulable
  container_property: startTime
  description: The actual start time of an activity (or similar that extends this)
  immutable: false
  index: startTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_2304763f_d0f3_4723_a4c5_2e879069195d
  nullable: true
  value_type: timestamp
  view: ClassicEvent
  view_property: startTime
- connection: direct
  container: cdf_cdm:CogniteFile
  container_property: assets
  description: A list of assets this file is related to.
  immutable: false
  is_list: true
  name: Assets
  neatId: http://purl.org/cognite/neat/neatId_77ec0da0_839b_4b52_9f64_35382213dac6
  nullable: true
  value_type: ClassicAsset
  view: ClassicFile
  view_property: assetIds
- container: cdf_cdm:CogniteFile
  container_property: directory
  description: Contains the path elements from the source (if the source system has
    a file system hierarchy or similar.)
  immutable: false
  is_list: false
  name: Directory
  neatId: http://purl.org/cognite/neat/neatId_f06ff883_4f00_4a5d_b9c3_83664b62b573
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: directory
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_5d721016_c99e_4f73_8e9d_bdd27b4472c3
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: labels
- container: cdf_cdm:CogniteFile
  container_property: mimeType
  description: The MIME type of the file.
  immutable: false
  is_list: false
  name: MIME type
  neatId: http://purl.org/cognite/neat/neatId_d65bd20a_bcb9_4243_b3e9_06188378c4cc
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: mimeType
- container: cdf_cdm:CogniteDescribable
  container_property: name
  description: Name of the instance
  immutable: false
  index: name
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_793d1480_2fba_4dde_8325_c11ef7e57de5
  nullable: true
  value_type: text
  view: ClassicFile
  view_property: name
- connection: direct
  container: cdf_cdm:CogniteSourceable
  container_property: source
  description: Direct relation to a source system
  immutable: false
  index: source
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_87aa809b_a7cc_4136_885c_276844ed6b38
  nullable: true
  value_type: ClassicSourceSystem
  view: ClassicFile
  view_property: source
- container: cdf_cdm:CogniteSourceable
  container_property: sourceCreatedTime
  description: When the instance was created in source system (if available)
  immutable: false
  index: sourceCreatedTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_26b7346d_3d5f_43a5_894e_96707e89227c
  nullable: true
  value_type: timestamp
  view: ClassicFile
  view_property: sourceCreatedTime
- container: cdf_cdm:CogniteSourceable
  container_property: sourceUpdatedTime
  description: When the instance was last updated in the source system (if available)
  immutable: false
  index: sourceUpdatedTime
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_4b6be7c8_8b26_4f11_9ad5_283123a54c91
  nullable: true
  value_type: timestamp
  view: ClassicFile
  view_property: sourceModifiedTime
- container: cdf_cdm:CogniteDescribable
  container_property: name
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_7d7c614a_43ea_4fc2_abb0_3f3fdddaa239
  nullable: true
  value_type: text
  view: ClassicSourceSystem
  view_property: name
- connection: direct
  container: cdf_cdm:CogniteTimeSeries
  container_property: assets
  description: A list of assets the time series is related to.
  immutable: false
  is_list: true
  name: Assets
  neatId: http://purl.org/cognite/neat/neatId_bc4e12b0_82bd_4859_995d_d219181f9b52
  nullable: true
  value_type: ClassicAsset
  view: ClassicTimeSeries
  view_property: assetId
- container: cdf_cdm:CogniteDescribable
  container_property: description
  description: Description of the instance
  immutable: false
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_73372a76_aa52_47c1_bdae_34bfbd80f572
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: description
- container: cdf_cdm:CogniteTimeSeries
  container_property: isStep
  default: 0
  description: Specifies whether the time series is a step time series or not.
  immutable: false
  is_list: false
  name: Is step
  neatId: http://purl.org/cognite/neat/neatId_cfa476ae_125b_4e6a_8caf_152f44095037
  nullable: false
  value_type: boolean
  view: ClassicTimeSeries
  view_property: isStep
- container: cdf_cdm:CogniteTimeSeries
  container_property: type
  description: Specifies the data type of the data points.
  immutable: true
  is_list: false
  name: Type
  neatId: http://purl.org/cognite/neat/neatId_7943437b_6138_47e6_889a_f414280df48e
  nullable: false
  value_type: enum(collection=timeseriesType)
  view: ClassicTimeSeries
  view_property: isString
- container: cdf_cdm:CogniteDescribable
  container_property: aliases
  description: Alternative names for the node
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_15cfc454_8fc0_443b_8af6_9db5368d6fd4
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: legacyName
- container: cdf_cdm:CogniteDescribable
  container_property: name
  description: Name of the instance
  immutable: false
  index: name
  is_list: false
  neatId: http://purl.org/cognite/neat/neatId_01370dd7_3371_40a1_b4eb_ddfcbbac63c8
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: name
- container: cdf_cdm:CogniteDescribable
  container_property: tags
  description: Text based labels for generic use, limited to 1000
  immutable: false
  is_list: true
  neatId: http://purl.org/cognite/neat/neatId_d7e122ee_421a_490f_9bec_b0f9f5ececfd
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: securityCategories
- container: cdf_cdm:CogniteTimeSeries
  container_property: sourceUnit
  description: The unit specified in the source system.
  immutable: false
  is_list: false
  name: Source unit
  neatId: http://purl.org/cognite/neat/neatId_3bfc11e0_9d27_47ea_841e_de1e4363dbed
  nullable: true
  value_type: text
  view: ClassicTimeSeries
  view_property: unit
- connection: direct
  container: cdf_cdm:CogniteTimeSeries
  container_property: unit
  description: The unit of the time series.
  immutable: false
  is_list: false
  name: Unit
  neatId: http://purl.org/cognite/neat/neatId_33b75362_e127_4a5a_9690_2df55501250c
  nullable: true
  value_type: cdf_cdm:CogniteUnit(version=v1)
  view: ClassicTimeSeries
  view_property: unitExternalId
views:
- description: Represents a single unit of measurement
  implements: cdf_cdm:CogniteDescribable(version=v1)
  in_model: true
  neatId: http://purl.org/cognite/neat/neatId_f3397b4c_b6e0_4701_8ea3_7edbf72bf50d
  view: cdf_cdm:CogniteUnit(version=v1)
- description: Assets represent systems that support industrial functions or processes.
    Assets are often called 'functional location'.
  implements: cdf_cdm:CogniteAsset(version=v1)
  in_model: true
  name: Asset
  neatId: http://purl.org/cognite/neat/neatId_23380192_0c8a_4870_9684_cb91e5e5d67d
  view: ClassicAsset
- description: Represents activities. Activities typically happen over a period and
    have a start and end time.
  implements: cdf_cdm:CogniteActivity(version=v1)
  in_model: true
  name: Activity
  neatId: http://purl.org/cognite/neat/neatId_3c0bda0e_9af0_4c75_9f1c_d76a6eae2e44
  view: ClassicEvent
- description: Represents files.
  implements: cdf_cdm:CogniteFile(version=v1)
  in_model: true
  name: File
  neatId: http://purl.org/cognite/neat/neatId_4a92bfcc_a259_4ec6_b58b_bdb386ba9ce2
  view: ClassicFile
- description: The CogniteSourceSystem core concept is used to standardize the way
    source system is stored.
  implements: cdf_cdm:CogniteSourceSystem(version=v1)
  in_model: true
  neatId: http://purl.org/cognite/neat/neatId_280264e2_a809_4feb_81e3_454adc00fdde
  view: ClassicSourceSystem
- description: Represents a series of data points in time order.
  implements: cdf_cdm:CogniteTimeSeries(version=v1)
  in_model: true
  name: Time series
  neatId: http://purl.org/cognite/neat/neatId_0730d4f7_51ce_40de_a8af_b9efff498b06
  view: ClassicTimeSeries
