configs: []
description: null
implementation_module: null
name: sheet2cdf
steps:
-   configs: null
    description: null
    enabled: true
    id: step_trigger
    label: Process trigger
    max_retries: 0
    method: null
    params:
        workflow_start_method: persistent_blocking
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
    - step_load_rules
    trigger: true
    ui_config:
        pos_x: 509
        pos_y: 93
-   configs:
        file_name: sheet2cdf-transformation-rules.xlsx
        validate_rules: 'True'
        validation_report_file: rules_validation_report.txt
        validation_report_storage_dir: rules_validation_report
        version: ''
    description: null
    enabled: true
    id: step_load_rules
    label: Load rules from file
    max_retries: 0
    method: LoadTransformationRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_reset_stores
    - step_configure_solution_store
    trigger: false
    ui_config:
        pos_x: 511
        pos_y: 165
-   configs: {}
    description: null
    enabled: true
    id: step_load_rules_into_store
    label: Load rules as data into solution graph
    max_retries: 0
    method: InstancesFromRulesToSolutionGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_generate_assets
    trigger: false
    ui_config:
        pos_x: 507
        pos_y: 459
-   configs: {}
    description: null
    enabled: true
    id: step_generate_assets
    label: Generate assets
    max_retries: 0
    method: GenerateCDFAssetsFromGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_generate_relations
    trigger: false
    ui_config:
        pos_x: 507
        pos_y: 556
-   configs: {}
    description: null
    enabled: true
    id: step_generate_relations
    label: Generate relationships
    max_retries: 0
    method: GenerateCDFRelationshipsFromGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_upload_assets
    trigger: false
    ui_config:
        pos_x: 507
        pos_y: 632
-   configs: {}
    description: null
    enabled: true
    id: step_upload_assets
    label: Upload assets
    max_retries: 0
    method: UploadCDFAssets
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_upload_relations
    trigger: false
    ui_config:
        pos_x: 505
        pos_y: 711
-   configs: {}
    description: null
    enabled: true
    id: step_upload_relations
    label: Upload relationships
    max_retries: 0
    method: UploadCDFRelationships
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
        pos_x: 506
        pos_y: 795
-   configs: {}
    description: null
    enabled: true
    id: step_create_cdf_labels
    label: Create CDF labels
    max_retries: 0
    method: CreateCDFLabels
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_load_rules_into_store
    trigger: false
    ui_config:
        pos_x: 508
        pos_y: 382
-   configs:
        db_server_api_root_url: ''
        disk_store_dir: solution-graph-store-2
        graph_name: solution
        init_procedure: reset
        sparql_query_url: ''
        sparql_update_url: ''
        store_type: oxigraph
    description: null
    enabled: true
    id: step_configure_solution_store
    label: Configure solution graph store
    max_retries: 0
    method: ConfigureGraphStore
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_create_cdf_labels
    trigger: false
    ui_config:
        pos_x: 509
        pos_y: 263
system_components:
-   description: null
    id: source_excel_sheet
    label: Transformation Rules
    transition_to:
    - excel2rdf_parser
    - cdf_classic_exporter
    ui_config:
        pos_x: 170
        pos_y: 10
-   description: null
    id: excel2rdf_parser
    label: Excel to Graph Parser
    transition_to:
    - source_graph
    ui_config:
        pos_x: 0
        pos_y: 80
-   description: null
    id: source_graph
    label: Source Graph
    transition_to:
    - in_memmory_store
    ui_config:
        pos_x: 0
        pos_y: 150
-   description: null
    id: in_memmory_store
    label: In-Memory Graph Database
    transition_to:
    - cdf_classic_exporter
    ui_config:
        pos_x: 0
        pos_y: 220
-   description: null
    id: cdf_classic_exporter
    label: CDF Classic Exporter
    transition_to:
    - cdf_classic
    ui_config:
        pos_x: 170
        pos_y: 330
-   description: null
    id: cdf_classic
    label: CDF Classic (Asset,Relationships, Labels)
    transition_to: null
    ui_config:
        pos_x: 170
        pos_y: 400
