configs:
  - group: LoadTransformationRules
    label: Full name of the rules file
    name: rules.file
    options: null
    required: false
    type: null
    value: Rules-Nordic44-to-TNT.xlsx
  - group: LoadTransformationRules
    label: Optional version of the rules file
    name: rules.version
    options: null
    required: false
    type: null
    value: ""
  - group: ConfigureDefaultGraphStores
    label:
      "Data store type for source graph. Supported: oxigraph, memory,file, graphdb,
      sparql. "
    name: source_rdf_store.type
    options: null
    required: false
    type: null
    value: oxigraph
  - group: ConfigureDefaultGraphStores
    label:
      "Data store type for solutioin graph. Supported: oxigraph, memory,file,
      graphdb, sparql"
    name: solution_rdf_store.type
    options: null
    required: false
    type: null
    value: oxigraph
  - group: ConfigureDefaultGraphStores
    label: Local directory for source graph store
    name: source_rdf_store.disk_store_dir
    options: null
    required: false
    type: null
    value: source-graph-store
  - group: ConfigureDefaultGraphStores
    label: Local directory for solution graph store
    name: solution_rdf_store.disk_store_dir
    options: null
    required: false
    type: null
    value: solution-graph-store
  - group: ConfigureDefaultGraphStores
    label: "Defines which stores to configure. Possible values: all, source, solution"
    name: stores_to_configure
    options: null
    required: false
    type: null
    value: all
  - group: ConfigureDefaultGraphStores
    label: Root url for graphdb or sparql endpoint
    name: solution_rdf_store.api_root_url
    options: null
    required: false
    type: null
    value: ""
  - group: InstancesFromRdfFileToSourceGraph
    label: File name of source graph data dump in RDF format
    name: source_rdf_store.file
    options: null
    required: false
    type: null
    value: source-graphs/Knowledge-Graph-Nordic44.xml
description: null
implementation_module: null
name: graph_to_asset_hierarchy
steps:
  - description: null
    enabled: true
    id: step_http_trigger
    label: Process trigger
    max_retries: 0
    method: null
    params:
      workflow_start_method: persistent_blocking
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
      - step_rules_loader
    trigger: true
    ui_config:
      pos_x: 455
      pos_y: 67
  - description: null
    enabled: true
    id: step_rules_loader
    label: Rules loader
    max_retries: 0
    method: LoadTransformationRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_234135
    trigger: false
    ui_config:
      pos_x: 456
      pos_y: 177
  - description: null
    enabled: true
    id: step_configure_graph_stores
    label: Configure graph stores
    max_retries: 0
    method: ConfigureDefaultGraphStores
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_create_labels
    trigger: false
    ui_config:
      pos_x: 455
      pos_y: 338
  - description: null
    enabled: true
    id: step_234135
    label: Reset graph stores
    max_retries: 0
    method: ResetGraphStores
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_configure_graph_stores
    trigger: false
    ui_config:
      pos_x: 456
      pos_y: 254
  - description: null
    enabled: true
    id: step_graph_loader
    label: Load graph from rdf file
    max_retries: 0
    method: InstancesFromRdfFileToSourceGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_transform
    trigger: false
    ui_config:
      pos_x: 455
      pos_y: 478
  - description: null
    enabled: true
    id: step_transform
    label: Transform graph
    max_retries: 0
    method: TransformSourceToSolutionGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_generate_assets
    trigger: false
    ui_config:
      pos_x: 457
      pos_y: 557
  - description: null
    enabled: true
    id: step_generate_assets
    label: Generate cdf assets
    max_retries: 0
    method: GenerateCDFAssetsFromGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_assets_uploader
    trigger: false
    ui_config:
      pos_x: 458
      pos_y: 655
  - description: null
    enabled: true
    id: step_assets_uploader
    label: Upload assets
    max_retries: 0
    method: UploadCDFAssets
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_generate_relationships
    trigger: false
    ui_config:
      pos_x: 457
      pos_y: 748
  - description: null
    enabled: true
    id: step_generate_relationships
    label: Generate relationships
    max_retries: 0
    method: GenerateCDFRelationshipsFromGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_upload_relationships
    trigger: false
    ui_config:
      pos_x: 452
      pos_y: 852
  - description: null
    enabled: true
    id: step_upload_relationships
    label: Upload relationships
    max_retries: 0
    method: UploadCDFRelationships
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
      pos_x: 457
      pos_y: 954
  - description: null
    enabled: true
    id: step_create_labels
    label: Create CDF labels
    max_retries: 0
    method: CreateCDFLabels
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_graph_loader
    trigger: false
    ui_config:
      pos_x: 455
      pos_y: 404
system_components:
  - description: null
    id: grid_management_system
    label: Grid management system
    transition_to:
      - rdf_xml_file
    ui_config:
      pos_x: 171
      pos_y: 6
  - description: null
    id: rdf_xml_file
    label: RDF XML File
    transition_to:
      - graph_db_store
    ui_config:
      pos_x: 170
      pos_y: 103
  - description: null
    id: graph_db_store
    label: OxiGraph source graph_store
    transition_to:
      - transformer
    ui_config:
      pos_x: 240
      pos_y: 177
  - description: null
    id: in_memmory_store
    label: In-memory source graph_store
    transition_to: []
    ui_config:
      pos_x: 73
      pos_y: 175
  - description: null
    id: transformation_rules
    label: Transformation rules
    transition_to:
      - transformer
    ui_config:
      pos_x: 413
      pos_y: 195
  - description: null
    id: cdf_raw_table
    label: Cdf raw lookup table
    transition_to:
      - transformer
    ui_config:
      pos_x: 586
      pos_y: 195
  - description: null
    id: transformer
    label: Transformer
    transition_to:
      - solution_graph
    ui_config:
      pos_x: 237
      pos_y: 329
  - description: null
    id: solution_graph
    label: Solution graph
    transition_to:
      - cdf_classic_exporter
    ui_config:
      pos_x: 237
      pos_y: 405
  - description: null
    id: cdf_classic_exporter
    label: CDF Classic exporter
    transition_to:
      - cdf_classic
    ui_config:
      pos_x: 181
      pos_y: 498
  - description: null
    id: cdf_fdm_exporter
    label: CDF FDM exporter
    transition_to:
      - cdf_fdm
    ui_config:
      pos_x: 345
      pos_y: 498
  - description: null
    id: cdf_classic
    label: CDF Classic (Asset,Relationships)
    transition_to: []
    ui_config:
      pos_x: 182
      pos_y: 586
  - description: null
    id: cdf_fdm
    label: CDF FDM
    transition_to: []
    ui_config:
      pos_x: 347
      pos_y: 586
