CFIHOS_TYPE_ENTITY = "entity"
CFIHOS_TYPE_EQUIPMENT = "equipment"
CFIHOS_TYPE_TAG = "tag"

CFIHOS_TYPE_ENTITY_PREFIX = ""
CFIHOS_TYPE_EQUIPMENT_PREFIX = "E"
CFIHOS_TYPE_TAG_PREFIX = "T"

CFIHOS_ID_ENTITY_PREFIX = "CFIHOS-0"
CFIHOS_ID_EQUIPMENT_PREFIX = "CFIHOS-3"
CFIHOS_ID_TAG_PREFIX = "CFIHOS-3"
CFIHOS_ID_PREFIX = "CFIHOS-"
