configs:
  - group: LoadTransformationRules
    label: Full name of the rules file
    name: rules.file
    options: null
    required: false
    type: null
    value: Rules-Nordic44-to-graphql.xlsx
  - group: LoadTransformationRules
    label: Optional version of the rules file
    name: rules.version
    options: null
    required: false
    type: null
    value: ""
  - group: GraphQLSchemaFromRules
    label: Name of the GraphQL schema file
    name: graphql_schema.file
    options: null
    required: false
    type: null
    value: data_model.graphql
  - group: GraphQLSchemaFromRules
    label: Directory to store GraphQL schema file
    name: graphql_export.storage_dir
    options: null
    required: false
    type: null
    value: staging
description: null
implementation_module: null
name: data_mode_generation
steps:
  - description: null
    enabled: true
    id: step_http_trigger
    label: HTTP process trigger
    max_retries: 0
    method: null
    params:
      workflow_start_method: persistent_blocking
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
      - step_load_rules
    trigger: true
    ui_config:
      pos_x: 545
      pos_y: 81
  - description: null
    enabled: true
    id: step_generate_graphql_file
    label: Generate GraphQL file
    max_retries: 0
    method: GraphQLSchemaFromRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
      pos_x: 549
      pos_y: 311
  - description: null
    enabled: true
    id: step_load_rules
    label: Load data model from rules file
    max_retries: 0
    method: LoadTransformationRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_generate_graphql_file
    trigger: false
    ui_config:
      pos_x: 543
      pos_y: 188
system_components:
  - description: null
    id: define_data_model
    label: User defines data model using Transformation Rules template
    transition_to:
      - convert_to_graphql
    ui_config:
      pos_x: 452
      pos_y: 106
  - description: null
    id: convert_to_graphql
    label: Convert Transformation Rules to FDM Schema
    transition_to:
      - download_fdm_schema
    ui_config:
      pos_x: 452
      pos_y: 216
  - description: null
    id: download_fdm_schema
    label: Download FDM Schema
    transition_to: []
    ui_config:
      pos_x: 452
      pos_y: 306
