configs: []
description: null
implementation_module: null
name: data_model_generation
steps:
-   configs: null
    description: null
    enabled: true
    id: step_http_trigger
    label: HTTP process trigger
    max_retries: 0
    method: null
    params:
        workflow_start_method: persistent_blocking
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
    - step_load_rules
    trigger: true
    ui_config:
        pos_x: 545
        pos_y: 81
-   configs:
        file_name: Rules-Nordic44-to-graphql.xlsx
        validate_rules: 'True'
        validation_report_file: rules_validation_report.txt
        validation_report_storage_dir: rules_validation_report
        version: ''
    description: null
    enabled: true
    id: step_load_rules
    label: Load Transformation Rules from Excel file
    max_retries: 0
    method: LoadTransformationRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_generate_graphql_file
    trigger: false
    ui_config:
        pos_x: 543
        pos_y: 165
-   configs:
        file_name: ''
        storage_dir: staging
    description: null
    enabled: true
    id: step_generate_graphql_file
    label: Generate GraphQL Schema from Transformation Rules
    max_retries: 0
    method: GraphQLSchemaFromRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_rules2ontology
    trigger: false
    ui_config:
        pos_x: 542
        pos_y: 269
-   configs:
        file_name: ''
        storage_dir: staging
        store_warnings: 'True'
    description: null
    enabled: true
    id: step_rules2ontology
    label: Generate Ontology from Transformation Rules
    max_retries: 0
    method: OntologyFromRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_rules2shacl
    trigger: false
    ui_config:
        pos_x: 541
        pos_y: 379
-   configs:
        file_name: ''
        storage_dir: staging
    description: null
    enabled: true
    id: step_rules2shacl
    label: Generate SHACL from Transformation Rules
    max_retries: 0
    method: SHACLFromRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
        pos_x: 542
        pos_y: 498
system_components:
-   description: null
    id: system_comp_define_data_model
    label: User defines data model using Transformation Rules template
    transition_to:
    - convert_to_graphql
    - system_comp_rules2graphql
    - system_comp_rules2ontology
    - system_comp_rules2shacl
    ui_config:
        pos_x: 653
        pos_y: 57
-   description: null
    id: system_comp_rules2graphql
    label: Convert Transformation Rules to GraphQL Schema
    transition_to:
    - download_fdm_schema
    - system_comp_download_graphql_schema
    ui_config:
        pos_x: 452
        pos_y: 216
-   description: null
    id: system_comp_download_graphql_schema
    label: Download GraphQL Schema
    transition_to: []
    ui_config:
        pos_x: 452
        pos_y: 306
-   description: null
    id: system_comp_rules2ontology
    label: Convert Transformation Rules to OWL Ontology
    transition_to:
    - system_comp_download_ontology
    ui_config:
        pos_x: 654
        pos_y: 216
-   description: null
    id: system_comp_rules2shacl
    label: Convert Transformation Rules to SHACL
    transition_to:
    - system_comp_213748
    ui_config:
        pos_x: 842
        pos_y: 218
-   description: null
    id: system_comp_download_ontology
    label: Download OWL Ontology
    transition_to: []
    ui_config:
        pos_x: 654
        pos_y: 305
-   description: null
    id: system_comp_213748
    label: Download SHACL Contraints
    transition_to: []
    ui_config:
        pos_x: 842
        pos_y: 308
