configs: []
description: null
implementation_module: null
name: dexpi2graph
steps:
  - configs: {}
    description: null
    enabled: true
    id: step_trigger
    label: Workflow Trigger
    max_retries: 0
    method: null
    params: {}
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
      - step_128344
      - step_configure_graph_store
    trigger: true
    ui_config:
      pos_x: 358
      pos_y: 103
  - configs:
      db_server_api_root_url: ""
      disk_store_dir: dexpi-graph
      graph_name: source
      init_procedure: reset
      sparql_query_url: ""
      sparql_update_url: ""
      store_type: oxigraph
    description: null
    enabled: true
    id: step_configure_graph_store
    label: Graph Store Config
    max_retries: 0
    method: ConfigureGraphStore
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_download_dexpi_file
    trigger: false
    ui_config:
      pos_x: 357
      pos_y: 180
  - configs:
      base_namespace: http://purl.org/cognite/neat#
      file_path: source-graphs/depxi_example.xml
    description: null
    enabled: true
    id: step_load_ttl
    label: DEXPI to Knowledge Graph
    max_retries: 0
    method: DexpiToGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
      pos_x: 359
      pos_y: 348
  - configs:
      api_url: https://raw.githubusercontent.com/cognitedata/neat/main/tests/data/depxi_example.xml
      auth_mode: none
      http_method: GET
      output_file_path: source-graphs/depxi_example.xml
      password: ""
      response_destination: file
      token: ""
      username: ""
    description: null
    enabled: true
    id: step_download_dexpi_file
    label: Download DISC DEXPI example
    max_retries: 0
    method: DownloadDataFromRestApiToFile
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_load_ttl
    trigger: false
    ui_config:
      pos_x: 358
      pos_y: 252
system_components: []
