configs: []
description: null
implementation_module: null
name: information2data_model
steps:
  - configs: {}
    description: null
    enabled: true
    id: step_trigger
    label: Trigger
    max_retries: 0
    method: null
    params: {}
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
      - step_128344
      - dowload_ontology
    trigger: true
    ui_config:
      pos_x: 524
      pos_y: 257
  - configs:
      excel_file_path: rules/LIS-14-rules.xlsx
      make_compliant: "True"
      ontology_file_path: staging/LIS-14.ttl
    description: null
    enabled: true
    id: onotology2rules
    label: Ontology to Rules
    max_retries: 0
    method: OntologyToRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - load_generated_rules
    trigger: false
    ui_config:
      pos_x: 522
      pos_y: 426
  - configs:
      file_name: LIS-14-rules.xlsx
      validation_report_file: rules_validation_report.txt
      validation_report_storage_dir: rules_validation_report
      version: ""
    description: null
    enabled: true
    id: load_generated_rules
    label: Load Generated Rules
    max_retries: 0
    method: LoadTransformationRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - step_59017
      - rules2graphql
    trigger: false
    ui_config:
      pos_x: 522
      pos_y: 506
  - configs:
      api_url: https://rds.posccaesar.org/ontology/lis14/ont/core/2.0/LIS-14.ttl
      auth_mode: none
      http_method: GET
      output_file_path: staging/LIS-14.ttl
      password: ""
      response_destination: file
      token: ""
      username: ""
    description: null
    enabled: true
    id: dowload_ontology
    label: Download Ontology
    max_retries: 0
    method: DownloadDataFromRestApiToFile
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
      - onotology2rules
    trigger: false
    ui_config:
      pos_x: 521
      pos_y: 339
  - configs:
      file_name: ""
      storage_dir: staging
    description: null
    enabled: true
    id: rules2graphql
    label: Rules to GraphQL Schema
    max_retries: 0
    method: GraphQLSchemaFromRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
      pos_x: 483
      pos_y: 583
system_components: []
