environment:
  name: dev
  project: get-power-grid
  type: dev
  selected:
  - neat_integration_runner

modules:
  modules:
    neat_integration_runner:
      source_id: df15ad2f-f037-462f-9089-43ff9fc95926
