configs:
-   group: source_rdf_store
    label: null
    name: source_rdf_store.api_root_url
    options: null
    required: false
    type: null
    value: http://graphdb:7200
-   group: source_rdf_store
    label: null
    name: graphdb_repo_name
    options: null
    required: false
    type: null
    value: nordic44
-   group: import_prefix
    label: null
    name: import_prefix
    options: null
    required: false
    type: null
    value: http://purl.org/nordic44
-   group: source_rdf_store
    label: null
    name: import_file_name
    options: null
    required: false
    type: null
    value: CGMES_2_4.zip
-   group: source_rdf_store
    label: null
    name: rdf_file_import.cdf_exteranl_id
    options: null
    required: false
    type: null
    value: null
-   group: source_rdf_store
    label: null
    name: rdf_file_import.shared_folder
    options: null
    required: false
    type: null
    value: /app/shared
description: null
system_components:
-   description: null
    id: grid_management_system
    label: Grid management system
    transition_to:
    - rdf_xml_file
    ui_config:
        pos_x: 171
        pos_y: 6
-   description: null
    id: rdf_xml_file
    label: RDF XML File
    transition_to:
    - graph_db_store
    ui_config:
        pos_x: 170
        pos_y: 103
-   description: null
    id: graph_db_store
    label: GraphDB source graph_store
    transition_to:
    - transformer
    ui_config:
        pos_x: 240
        pos_y: 177
-   description: null
    id: in_memmory_store
    label: In-memory source graph_store
    transition_to: null
    ui_config:
        pos_x: 73
        pos_y: 175
-   description: null
    id: transformation_rules
    label: Transformation rules
    transition_to:
    - transformer
    ui_config:
        pos_x: 413
        pos_y: 195
-   description: null
    id: cdf_raw_table
    label: Cdf raw lookup table
    transition_to:
    - transformer
    ui_config:
        pos_x: 586
        pos_y: 195
-   description: null
    id: transformer
    label: Transformer
    transition_to:
    - solution_graph
    ui_config:
        pos_x: 237
        pos_y: 329
-   description: null
    id: solution_graph
    label: Solution graph
    transition_to:
    - cdf_classic_exporter
    ui_config:
        pos_x: 237
        pos_y: 405
-   description: null
    id: cdf_classic_exporter
    label: CDF Classic exporter
    transition_to:
    - cdf_classic
    ui_config:
        pos_x: 181
        pos_y: 498
-   description: null
    id: cdf_fdm_exporter
    label: CDF FDM exporter
    transition_to:
    - cdf_fdm
    ui_config:
        pos_x: 345
        pos_y: 498
-   description: null
    id: cdf_classic
    label: CDF Classic (Asset,Relationships)
    transition_to: null
    ui_config:
        pos_x: 182
        pos_y: 586
-   description: null
    id: cdf_fdm
    label: CDF FDM
    transition_to: null
    ui_config:
        pos_x: 347
        pos_y: 586
implementation_module: null
name: graph_db_import
steps:
-   description: null
    enabled: true
    group_id: null
    id: create_repository
    label: Creating GraphDB repository
    method: null
    params: null
    stype: pystep
    transition_to:
    - load_source_graph
    trigger: false
    ui_config:
        pos_x: 110
        pos_y: 192
-   description: null
    enabled: true
    group_id: null
    id: load_source_graph
    label: Importing file into the repository
    method: null
    params: null
    stype: pystep
    transition_to:
    - wait_for_import_completion
    trigger: false
    ui_config:
        pos_x: 110
        pos_y: 282
-   description: null
    enabled: true
    group_id: null
    id: wait_for_import_completion
    label: Waiting for import operation status report
    method: null
    params: null
    stype: pystep
    transition_to: []
    trigger: false
    ui_config:
        pos_x: 111
        pos_y: 378
-   description: null
    enabled: true
    group_id: null
    id: step_http_trigger
    label: HTTP trigger
    method: null
    params: {}
    stype: http_trigger
    transition_to:
    - download_files_from_cdf
    trigger: true
    ui_config:
        pos_x: 95
        pos_y: -27
-   description: null
    enabled: false
    group_id: null
    id: step_time_trigger
    label: Time trigger
    method: null
    params:
        interval: every 5 minutes
    stype: time_trigger
    transition_to:
    - download_files_from_cdf
    trigger: true
    ui_config:
        pos_x: 264
        pos_y: -25
-   description: null
    enabled: true
    group_id: null
    id: download_files_from_cdf
    label: Downloading files from cdf
    method: null
    params: {}
    stype: pystep
    transition_to:
    - create_repository
    trigger: false
    ui_config:
        pos_x: 110
        pos_y: 102
