configs: []
description: null
implementation_module: null
name: skos2cdf
steps:
-   configs: {}
    description: null
    enabled: true
    id: step_trigger
    label: Workflow Trigger
    max_retries: 0
    method: null
    params: {}
    retry_delay: 3
    stype: http_trigger
    system_component_id: null
    transition_to:
    - step_load_rules
    trigger: true
    ui_config:
        pos_x: 492
        pos_y: 89
-   configs:
        file_name: skos-rules.xlsx
        validation_report_file: rules_validation_report.txt
        validation_report_storage_dir: rules_validation_report
        version: ''
    description: null
    enabled: true
    id: step_load_rules
    label: Load SKOS Rules
    max_retries: 0
    method: LoadTransformationRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_506363
    - step_configure_graph_store
    trigger: false
    ui_config:
        pos_x: 492
        pos_y: 153
-   configs:
        base_namespace: http://purl.org/neat/
        file_path: source-graphs/skos-capturing-sheet-wind-topics.xlsx
        graph_name: source
    description: null
    enabled: true
    id: step_process_graph_capturing_sheet
    label: Extract Triples from Graph Capturing Sheet
    max_retries: 0
    method: GraphCapturingSheetToGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_generate_dms_data_model
    trigger: false
    ui_config:
        pos_x: 491
        pos_y: 273
-   configs:
        db_server_api_root_url: ''
        disk_store_dir: skos-graph-store
        graph_name: source
        init_procedure: reset
        sparql_query_url: ''
        sparql_update_url: ''
        store_type: oxigraph
    description: null
    enabled: true
    id: step_configure_graph_store
    label: Configure Graph Store
    max_retries: 0
    method: ConfigureGraphStore
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_process_graph_capturing_sheet
    trigger: false
    ui_config:
        pos_x: 491
        pos_y: 212
-   configs: {}
    description: null
    enabled: true
    id: step_generate_dms_data_model
    label: Generate DMS Data Model
    max_retries: 0
    method: DMSDataModelFromRules
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_generate_nodes_and_edges
    trigger: false
    ui_config:
        pos_x: 490
        pos_y: 348
-   configs:
        add_class_prefix: 'False'
        data_validatation_error_handling_strategy: skip_and_report
        graph_name: source
    description: null
    enabled: true
    id: step_generate_nodes_and_edges
    label: Generate Nodes & Edges from Triples
    max_retries: 0
    method: GenerateCDFNodesAndEdgesFromGraph
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_upload_data_model
    trigger: false
    ui_config:
        pos_x: 490
        pos_y: 424
-   configs: {}
    description: null
    enabled: true
    id: step_upload_data_model
    label: Upload DMS Data Model
    max_retries: 0
    method: UploadDMSDataModel
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_upload_nodes
    trigger: false
    ui_config:
        pos_x: 489
        pos_y: 502
-   configs: {}
    description: null
    enabled: true
    id: step_upload_nodes
    label: Upload Nodes
    max_retries: 0
    method: UploadCDFNodes
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to:
    - step_upload_edges
    trigger: false
    ui_config:
        pos_x: 488
        pos_y: 579
-   configs: {}
    description: null
    enabled: true
    id: step_upload_edges
    label: Upload Edges
    max_retries: 0
    method: UploadCDFEdges
    params: {}
    retry_delay: 3
    stype: stdstep
    system_component_id: null
    transition_to: []
    trigger: false
    ui_config:
        pos_x: 488
        pos_y: 640
system_components: []
