cdf_client:
    project: get-power-grid
    client_id: ca4b8f9c6-7d6e-4d7b-9cf3-6d4a32f8b7e1
    client_secret: Zy7!nM4cFp9sH3gR6tB8kL0oP7eU6wD5vQ4zN9yF
    client_name: neat-test-service
    base_url: https://az-power-no-northeurope.cognitedata.com
    scopes:
      - https://az-power-no-northeurope.cognitedata.com/.default
    token_url: https://login.microsoftonline.com/12a3b456-789c-0d1e-2f3a-4b56c78d9e0f/oauth2/v2.0/token

workflows_store_type: file
cdf_default_dataset_id: 3931920688237191
workflow_downloader_filter:
    - tag:grid
log_level: DEBUG
