name: Build and Publish Neat Docker Container on Release

on:
  # push:
  #   branches:
  #     - docker-builder-publisher
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment: CD
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.1

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Export dependencies
        run: |
          poetry export -f requirements.txt --output requirements.txt --extras "all"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: cognite/neat:latest, cognite/neat:${{ github.ref_name }}

  build-and-push-f25e:
    runs-on: ubuntu-latest
    environment: main
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.3.4

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: 7e26ba04-3da0-4241-b517-c12b8205af8a
          tenant-id: a9ae5b54-3600-4917-a9dc-3020723360b3
          subscription-id: fd108646-dc13-4d9a-9b8c-d9dbde664887

      - name: Export dependencies
        run: |
          poetry export -f requirements.txt --output requirements.txt --extras "all"

      - id: version
        name: Build Version
        run: echo "version=$(date -u '+%Y%m%dT%H%M%SZ')"  >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        env:
          VERSION: ${{ env.version }}
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: scsproduction.azurecr.io/neat:${{ env.version }}
